name: TeamCity DSL to GHA Converter

on:
  push:
    paths:
      - 'teamcity_dsl/*.kt'

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install openai
      - name: Convert TeamCity DSL to YAML
        run: python ai_conversion/convert.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
